baseurl = "/feathergui"
languageCode = "en-us"
title = "FeatherGUI"
theme = "featherdocs"
author = "Erik McClure"
copyright = "Black Sphere Studios. All rights reserved."
publishdir = "../"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Web Designer"
    pre = "<i class='fa fa-cloud fa-fw'></i>"
    weight = 1
    identifier = "web"
    url = "/web/"
  [[menu.main]]
    name = "Download"
    pre = "<i class='fa fa-download fa-fw'></i>"
    weight = 2
    identifier = "dl"
    url = "/dl/"
  [[menu.main]]
    name = "Documentation"
    pre = "<i class='fa fa-book fa-fw'></i>"
    weight = 3
    identifier = "doc"
    url = "/doc/"
  [[menu.main]]
    name = "Github"
    pre = "<i class='fa fa-github fa-fw'></i>"
    weight = 4
    identifier = "github"
    url = "https://github.com/Black-Sphere-Studios/feathergui"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 5
    identifier = "about"
    url = "/about/"
    
[social]
  twitter = "bspherestudios"
  facebook = "BlackSphereStudios"
  github = "Black-Sphere-Studios/feathergui"
  linkedin = "company/black-sphere-studios"
